project_id = "xnatrxbdimhgyryssfff"

[functions.booking-notifications]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.send-reminder]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.track-booking]
verify_jwt = false

[functions.daily-summary-sms]
verify_jwt = false

[functions.daily-backup]
verify_jwt = false

[functions.site-backup]
verify_jwt = false

[functions.site-restore]
verify_jwt = false
